name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      # Use cache for npm dependencies
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Combine environment variable setup
      - name: Set up environment variables
        run: |
          export TNS_ADMIN=/actions-runner/_work/instantclient_19_8/network/admin
          export LD_LIBRARY_PATH=/actions-runner/_work/instantclient_19_8:$LD_LIBRARY_PATH
          echo "${{ secrets.PROD_ENV }}" > .env

      # Use Node.js with cache
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Conditional execution based on branch (combined)
      - name: Install dependencies (prod branches)
        if: github.ref != 'refs/heads/dev'
        run: npm ci

      - name: Run tests (prod branches)
        if: github.ref != 'refs/heads/dev'
        run: npm test

      - name: Skip npm ci and npm test for dev branch
        if: github.ref == 'refs/heads/dev'
        run: echo "Skipping npm ci and npm test for the dev branch"

      # Build Docker image using multi-stage build
      - name: Build Docker image
        run: docker build --pull --rm -t node-express-getting-started -f DOCKERFILE .

      # Remove previous container (unchanged)
      - name: Stop previous container if running
        run: |
          if [ "$(docker ps -q -f name=node-express-getting-started)" ]; then
            docker kill node-express-getting-started
          fi

      # Run Docker container (unchanged)
      - name: Run Docker container
        run: docker run --rm -d -p 3000:3000 --name node-express-getting-started node-express-getting-started:latest